/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_jokester_tidyj_TidyDoc */

#ifndef _Included_io_jokester_tidyj_TidyDoc
#define _Included_io_jokester_tidyj_TidyDoc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_jokester_tidyj_TidyDoc
 * Method:    nativeInit
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_io_jokester_tidyj_TidyDoc_nativeInit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_jokester_tidyj_TidyDoc
 * Method:    nativeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_jokester_tidyj_TidyDoc_nativeFree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_jokester_tidyj_TidyDoc
 * Method:    nativeParseString
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_jokester_tidyj_TidyDoc_nativeParseString
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     io_jokester_tidyj_TidyDoc
 * Method:    nativeParseStream
 * Signature: (JLjava/io/InputStream;)I
 */
JNIEXPORT jint JNICALL Java_io_jokester_tidyj_TidyDoc_nativeParseStream
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     io_jokester_tidyj_TidyDoc
 * Method:    nativeClean
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_jokester_tidyj_TidyDoc_nativeClean
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_jokester_tidyj_TidyDoc
 * Method:    nativeSetBoolOption
 * Signature: (JLjava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_io_jokester_tidyj_TidyDoc_nativeSetBoolOption
  (JNIEnv *, jobject, jlong, jstring, jboolean);

/*
 * Class:     io_jokester_tidyj_TidyDoc
 * Method:    nativeSetStringOption
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_jokester_tidyj_TidyDoc_nativeSetStringOption
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     io_jokester_tidyj_TidyDoc
 * Method:    nativeSetIntOption
 * Signature: (JLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_io_jokester_tidyj_TidyDoc_nativeSetIntOption
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     io_jokester_tidyj_TidyDoc
 * Method:    nativeSetAnyOption
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_jokester_tidyj_TidyDoc_nativeSetAnyOption
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     io_jokester_tidyj_TidyDoc
 * Method:    nativeWriteStream
 * Signature: (JLjava/io/OutputStream;)I
 */
JNIEXPORT jint JNICALL Java_io_jokester_tidyj_TidyDoc_nativeWriteStream
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
