/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_jokester_tidyj_TidyJ */

#ifndef _Included_io_jokester_tidyj_TidyJ
#define _Included_io_jokester_tidyj_TidyJ
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_jokester_tidyj_TidyJ
 * Method:    nativeInit
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_io_jokester_tidyj_TidyJ_nativeInit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_jokester_tidyj_TidyJ
 * Method:    nativeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_jokester_tidyj_TidyJ_nativeFree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_jokester_tidyj_TidyJ
 * Method:    nativeParse
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_jokester_tidyj_TidyJ_nativeParse__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     io_jokester_tidyj_TidyJ
 * Method:    nativeParse
 * Signature: (Ljava/io/PushbackInputStream;)I
 */
JNIEXPORT jint JNICALL Java_io_jokester_tidyj_TidyJ_nativeParse__Ljava_io_PushbackInputStream_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_jokester_tidyj_TidyJ
 * Method:    nativeSetBoolOption
 * Signature: (JLjava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_io_jokester_tidyj_TidyJ_nativeSetBoolOption
  (JNIEnv *, jobject, jlong, jstring, jboolean);

/*
 * Class:     io_jokester_tidyj_TidyJ
 * Method:    nativeSetStringOption
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_jokester_tidyj_TidyJ_nativeSetStringOption
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     io_jokester_tidyj_TidyJ
 * Method:    nativeSetIntOption
 * Signature: (JLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_io_jokester_tidyj_TidyJ_nativeSetIntOption
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     io_jokester_tidyj_TidyJ
 * Method:    nativeSetAnyOption
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_jokester_tidyj_TidyJ_nativeSetAnyOption
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     io_jokester_tidyj_TidyJ
 * Method:    nativeWriteStream
 * Signature: (JLjava/io/OutputStream;)I
 */
JNIEXPORT jint JNICALL Java_io_jokester_tidyj_TidyJ_nativeWriteStream
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
