/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_jokester_tidyj_TidyHTML5 */

#ifndef _Included_io_jokester_tidyj_TidyHTML5
#define _Included_io_jokester_tidyj_TidyHTML5
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_jokester_tidyj_TidyHTML5
 * Method:    initLibTidy
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_jokester_tidyj_TidyHTML5_initLibTidy
  (JNIEnv *, jobject);

/*
 * Class:     io_jokester_tidyj_TidyHTML5
 * Method:    nativeParseString
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_jokester_tidyj_TidyHTML5_nativeParseString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
